# Generated by Django 4.2.7 on 2024-04-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_basic_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('Session', 'Session'), ('Camp', 'Camp'), ('Drop-in', 'Drop-in'), ('Party', 'Party')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, choices=[('Aberdeen', 'Aberdeen'), ('Barnhartvale', 'Barnhartvale'), ('Batchlor Heights', 'Batchlor Heights'), ('Brocklehurst', 'Brocklehurst'), ('Campble Creek', 'Campble Creek'), ('Dallas', 'Dallas'), ('Downtown', 'Downtown'), ('Harper Mountain', 'Harper Mountain'), ('Juniper Ridge', 'Juniper Ridge'), ('Kamloops', 'Kamloops'), ('McArthur Island', 'McArthur Island'), ('North Kamloops', 'North Kamloops'), ('Rayleigh / Heffley', 'Rayleigh / Heffley'), ('Sahali Lower', 'Sahali Lower'), ('Sahali Upper', 'Sahali Upper'), ('Sun Peaks', 'Sun Peaks'), ('TRU', 'TRU'), ('Valleyview', 'Valleyview'), ('Westsyde', 'Westsyde')], max_length=20, null=True),
        ),
    ]
