# Generated by Django 4.2.7 on 2024-04-12 22:38

from django.db import migrations, models

AD_LOCATIONS = [
    ('H', 'Homepage Top Ads'),
    ('S', 'Search Results Top Ads'),
    ('S1', 'Search Results Sidebar #1 Ads'),
    ('S2', 'Search Results Sidebar #2 Ads'),
    ('C1', 'Categories Top-left Ads'),
    ('C2', 'Categories Top-middle Ads'),
    ('C3', 'Categories Top-right Ads'),
    ('SC', 'Specific Category Sidebar Ads'),

]

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('location', models.CharField(blank=True, choices=AD_LOCATIONS, max_length=2, null=True)),
            ],
        ),
    ]
