# Generated by Django 4.2.7 on 2023-12-20 13:22

import os
import random
from django.conf import settings
from django.db import migrations
from dotenv import load_dotenv

load_dotenv(override=True)


class Migration(migrations.Migration):

    def custom_task(apps, schema_editor):
            #('H', 'Homepage Top Ads'),
            #('S', 'Search Results Top Ads'),
            #('S1', 'Search Results Sidebar #1 Ads'),
            #('S2', 'Search Results Sidebar #2 Ads'),
            #('C1', 'Categories Top-left Ads'),
            #('C2', 'Categories Top-middle Ads'),
            #('C3', 'Categories Top-right Ads'),
            #('SC', 'Specific Category Sidebar Ads'),
        to_create = [
            {
                "image_url": "https://activity-guide-bucket.s3.ca-central-1.amazonaws.com/ads/home_page.jpg",
                "location": "H",
            },
            {
                "image_url": "https://activity-guide-bucket.s3.ca-central-1.amazonaws.com/ads/search_results_1.png",
                "location": "S",
            },
            {
                "image_url": "https://activity-guide-bucket.s3.ca-central-1.amazonaws.com/ads/search_results_2.png",
                "location": "S1",
            },
            {
                "image_url": "https://activity-guide-bucket.s3.ca-central-1.amazonaws.com/ads/search_results_3.png",
                "location": "S2",
            },
            {
                "image_url": "https://activity-guide-bucket.s3.ca-central-1.amazonaws.com/ads/categories_1.png",
                "location": "C1",
            },
            {
                "image_url": "https://activity-guide-bucket.s3.ca-central-1.amazonaws.com/ads/categories_2.png",
                "location": "C2",
            },
            {
                "image_url": "https://activity-guide-bucket.s3.ca-central-1.amazonaws.com/ads/categories_3.png",
                "location": "C3",
            }
        ]

        Ad = apps.get_model('ads', 'Ad')

        for ad in to_create:
            Ad.objects.create(
                image_url=ad['image_url'],
                location=ad['location'],
            )

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(custom_task, migrations.RunPython.noop),
    ]
