# Generated by Django 4.2.7 on 2023-12-18 22:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    # Creates 20 basic activities per category (Sports, Art, and Science)
    def custom_task(self, schema_editor):
        to_create = [
            # 20 Sports offers
            {
                "name": "Soccer",
                "description": "Team-based sport involving kicking a ball into the opponent's goal. Develops teamwork, coordination, and agility.",
                "category": "sports",
                "slugName": "soccer",
                "providerSlug": "playful-learning"
            },
            {
                "name": "Basketball",
                "description": "Fast-paced sport where two teams compete to score points by shooting a ball through the opponent's hoop. Enhances agility and teamwork.",
                "category": "sports",
                "slugName": "basketball",
                "providerSlug": "little-athlete"
            },
            {
                "name": "Swimming",
                "description": "Water-based activity involving various strokes to move through the water. Promotes fitness, endurance, and water safety.",
                "category": "sports",
                "slugName": "swimming",
                "providerSlug": "adventure-seekers"
            },
            {
                "name": "Gymnastics",
                "description": "Artistic and rhythmic exercises requiring strength, flexibility, and coordination. Builds physical fitness and body awareness.",
                "category": "sports",
                "slugName": "gymnastics",
                "providerSlug": "artistic-explorers"
            },
            {
                "name": "Tennis",
                "description": "Racket sport played between two players or pairs. Improves hand-eye coordination, agility, and strategic thinking.",
                "category": "sports",
                "slugName": "tennis",
                "providerSlug": "language-explorers"
            },
            {
                "name": "Baseball",
                "description": "Bat-and-ball sport with teams taking turns batting and fielding. Enhances hand-eye coordination, teamwork, and strategic thinking.",
                "category": "sports",
                "slugName": "baseball",
                "providerSlug": "little-athlete"
            },
            {
                "name": "Athletics",
                "description": "Track and field events including running, jumping, and throwing. Promotes overall fitness, speed, and endurance.",
                "category": "sports",
                "slugName": "athletics",
                "providerSlug": "super-chef-junior"
            },
            {
                "name": "Karate",
                "description": "Martial art focused on strikes, kicks, and blocks. Builds discipline, self-defense skills, and physical fitness.",
                "category": "sports",
                "slugName": "karate",
                "providerSlug": "adventure-seekers"
            },
            {
                "name": "Cycling",
                "description": "Sport or recreational activity of riding bicycles. Improves cardiovascular health, leg strength, and coordination.",
                "category": "sports",
                "slugName": "cycling",
                "providerSlug": "tech-tots-coding"
            },
            {
                "name": "Volleyball",
                "description": "Team sport where players use their hands to hit a ball over a net. Enhances teamwork, coordination, and agility.",
                "category": "sports",
                "slugName": "volleyball",
                "providerSlug": "adventure-seekers"
            },
            {
                "name": "Archery",
                "description": "Sport involving using a bow to shoot arrows at a target. Develops focus, precision, and upper body strength.",
                "category": "sports",
                "slugName": "archery",
                "providerSlug": "robot-builders"
            },
            {
                "name": "Hockey",
                "description": "Fast-paced sport played on a field or rink, involving hitting a ball or puck into the opponent's goal. Enhances teamwork and stick-handling skills.",
                "category": "sports",
                "slugName": "hockey",
                "providerSlug": "playful-learning"
            },
            {
                "name": "Golf",
                "description": "Precision sport where players use clubs to hit balls into a series of holes on a course. Develops focus, precision, and patience.",
                "category": "sports",
                "slugName": "golf",
                "providerSlug": "little-athlete"
            },
            {
                "name": "Badminton",
                "description": "Racket sport played with a shuttlecock, requiring fast reflexes and agility. Enhances hand-eye coordination and cardiovascular fitness.",
                "category": "sports",
                "slugName": "badminton",
                "providerSlug": "adventure-seekers"
            },
            {
                "name": "Table Tennis",
                "description": "Fast-paced indoor sport played with small paddles and a lightweight ball on a rectangular table. Enhances reflexes and coordination.",
                "category": "sports",
                "slugName": "table-tennis",
                "providerSlug": "artistic-explorers"
            },
            {
                "name": "Rugby",
                "description": "Contact sport played with an oval ball, involving running, passing, and tackling. Builds teamwork, strength, and endurance.",
                "category": "sports",
                "slugName": "rugby",
                "providerSlug": "language-explorers"
            },
            {
                "name": "Martial Arts",
                "description": "Various disciplines of combat and self-defense, promoting physical fitness, discipline, and mental focus.",
                "category": "sports",
                "slugName": "martial-arts",
                "providerSlug": "little-athlete"
            },
            {
                "name": "Rock Climbing",
                "description": "Sport or recreational activity of climbing indoor or outdoor rock walls. Builds strength, endurance, and problem-solving skills.",
                "category": "sports",
                "slugName": "rock-climbing",
                "providerSlug": "super-chef-junior"
            },
            {
                "name": "Skateboarding",
                "description": "Action sport involving riding and performing tricks on a skateboard. Enhances balance, coordination, and creativity.",
                "category": "sports",
                "slugName": "skateboarding",
                "providerSlug": "adventure-seekers"
            },
            {
                "name": "Fencing",
                "description": "Combat sport involving duels with bladed weapons. Develops agility, focus, and strategic thinking.",
                "category": "sports",
                "slugName": "fencing",
                "providerSlug": "tech-tots-coding"
            },
            {
                "name": "Surfing",
                "description": "Water sport involving riding waves on a surfboard. Enhances balance, coordination, and a connection to nature.",
                "category": "sports",
                "slugName": "surfing",
                "providerSlug": "adventure-seekers"
            },
            
            # 20 Art offers
            {
                "name": "Painting Workshop",
                "description": "Creative painting sessions for artistic expression. Explore various techniques and styles.",
                "category": "art",
                "slugName": "painting-workshop",
                "providerSlug": "artistic-explorers"
            },
            {
                "name": "Pottery Class",
                "description": "Hands-on pottery experience to mold and create unique clay masterpieces.",
                "category": "art",
                "slugName": "pottery-class",
                "providerSlug": "crafty-creations"
            },
            {
                "name": "Dance Class",
                "description": "Expressive dance classes to learn different dance styles and foster creativity.",
                "category": "art",
                "slugName": "dance-class",
                "providerSlug": "dance-magic"
            },
            {
                "name": "Music Ensemble",
                "description": "Collaborative music sessions to explore instruments and create harmonious tunes.",
                "category": "art",
                "slugName": "music-ensemble",
                "providerSlug": "musical-melodies"
            },
            {
                "name": "Photography Workshop",
                "description": "Introduction to photography techniques and artistic composition.",
                "category": "art",
                "slugName": "photography-workshop",
                "providerSlug": "language-explorers"
            },
            {
                "name": "Crafting Bonanza",
                "description": "Craft and DIY activities to unleash creativity and make unique projects.",
                "category": "art",
                "slugName": "crafting-bonanza",
                "providerSlug": "crafty-creations"
            },
            {
                "name": "Theater Arts Camp",
                "description": "Immersive theater experiences, including acting, scriptwriting, and stage performances.",
                "category": "art",
                "slugName": "theater-arts-camp",
                "providerSlug": "imagination-theater"
            },
            {
                "name": "Ceramics Studio",
                "description": "Specialized studio for creating intricate ceramic artworks with guidance from experts.",
                "category": "art",
                "slugName": "ceramics-studio",
                "providerSlug": "crafty-creations"
            },
            {
                "name": "Fashion Design Class",
                "description": "Explore the world of fashion design, from sketching to creating wearable art.",
                "category": "art",
                "slugName": "fashion-design-class",
                "providerSlug": "artistic-explorers"
            },
            {
                "name": "Sculpture Sculptors",
                "description": "Sculpting workshops for creating three-dimensional artworks using various materials.",
                "category": "art",
                "slugName": "sculpture-sculptors",
                "providerSlug": "crafty-creations"
            },
            {
                "name": "Street Art Crew",
                "description": "Explore street art techniques, including graffiti and mural creation.",
                "category": "art",
                "slugName": "street-art-crew",
                "providerSlug": "imagination-theater"
            },
            {
                "name": "Calligraphy Class",
                "description": "Master the art of calligraphy with beautiful lettering and artistic styles.",
                "category": "art",
                "slugName": "calligraphy-class",
                "providerSlug": "language-explorers"
            },
            {
                "name": "Digital Art Lab",
                "description": "Create digital art using various software and tools to express artistic visions.",
                "category": "art",
                "slugName": "digital-art-lab",
                "providerSlug": "science-wonders"
            },
            {
                "name": "Comic Book Creators",
                "description": "Learn the art of comic book creation, from storytelling to illustrating.",
                "category": "art",
                "slugName": "comic-book-creators",
                "providerSlug": "language-explorers"
            },
            {
                "name": "Ballet Academy",
                "description": "Structured ballet training for dancers to develop grace, technique, and performance skills.",
                "category": "art",
                "slugName": "ballet-academy",
                "providerSlug": "dance-magic"
            },
            {
                "name": "Mixed Media Madness",
                "description": "Explore mixed media art by combining various materials and techniques for unique creations.",
                "category": "art",
                "slugName": "mixed-media-madness",
                "providerSlug": "artistic-explorers"
            },
            {
                "name": "Jazz Music Jam",
                "description": "Jazz music sessions for young musicians to explore improvisation and ensemble playing.",
                "category": "art",
                "slugName": "jazz-music-jam",
                "providerSlug": "musical-melodies"
            },
            {
                "name": "Puppetry Playhouse",
                "description": "Puppetry workshops to create and perform with unique puppets and characters.",
                "category": "art",
                "slugName": "puppetry-playhouse",
                "providerSlug": "imagination-theater"
            },
            {
                "name": "Abstract Art Explorers",
                "description": "Expressive journey into abstract art, exploring color, form, and self-expression.",
                "category": "art",
                "slugName": "abstract-art-explorers",
                "providerSlug": "science-wonders"
            },
            {
                "name": "Folk Music Fiesta",
                "description": "Celebration of folk music traditions with hands-on experiences in playing traditional instruments.",
                "category": "art",
                "slugName": "folk-music-fiesta",
                "providerSlug": "musical-melodies"
            },

            # 20 Science offers
            {
                "name": "Chemistry Lab Explorers",
                "description": "Hands-on experiments exploring chemical reactions and fundamental principles of chemistry.",
                "category": "science",
                "slugName": "chemistry-lab-explorers",
                "providerSlug": "science-wonders"
            },
            {
                "name": "Astronomy Adventure Camp",
                "description": "Explore the wonders of the universe, including stars, planets, and galaxies.",
                "category": "science",
                "slugName": "astronomy-adventure-camp",
                "providerSlug": "playful-learning"
            },
            {
                "name": "Robotics Workshop",
                "description": "Introduction to robotics, programming, and building simple robots for hands-on learning.",
                "category": "science",
                "slugName": "robotics-workshop",
                "providerSlug": "robot-builders"
            },
            {
                "name": "Environmental Explorers",
                "description": "Learn about ecosystems, conservation, and environmental science through outdoor activities.",
                "category": "science",
                "slugName": "environmental-explorers",
                "providerSlug": "nature-discovery"
            },
            {
                "name": "Physics Fun Fair",
                "description": "Interactive physics experiments and demonstrations to explore principles of motion, energy, and forces.",
                "category": "science",
                "slugName": "physics-fun-fair",
                "providerSlug": "science-wonders"
            },
            {
                "name": "Paleontology Quest",
                "description": "Dive into the world of dinosaurs and fossils with hands-on paleontological activities.",
                "category": "science",
                "slugName": "paleontology-quest",
                "providerSlug": "nature-discovery"
            },
            {
                "name": "Microbiology Marvels",
                "description": "Explore the microscopic world of bacteria and microorganisms through lab experiments.",
                "category": "science",
                "slugName": "microbiology-marvels",
                "providerSlug": "science-wonders"
            },
            {
                "name": "Coding for Kids",
                "description": "Introduction to coding and computer science concepts through fun and interactive activities.",
                "category": "science",
                "slugName": "coding-for-kids",
                "providerSlug": "tech-tots-coding"
            },
            {
                "name": "Zoology Zoo",
                "description": "Discover the diversity of animal life through hands-on experiences, games, and activities.",
                "category": "science",
                "slugName": "zoology-zoo",
                "providerSlug": "animal-safari"
            },
            {
                "name": "Geology Rocks!",
                "description": "Explore the Earth's geological features, rocks, and minerals through exciting experiments.",
                "category": "science",
                "slugName": "geology-rocks",
                "providerSlug": "nature-discovery"
            },
            {
                "name": "Space Exploration Club",
                "description": "Journey into space exploration, including rocket building and astronomy activities.",
                "category": "science",
                "slugName": "space-exploration-club",
                "providerSlug": "playful-learning"
            },
            {
                "name": "Weather Watchers",
                "description": "Learn about meteorology and weather phenomena through experiments and observations.",
                "category": "science",
                "slugName": "weather-watchers",
                "providerSlug": "nature-discovery"
            },
            {
                "name": "Electricity and Magnetism Lab",
                "description": "Hands-on experiments exploring the principles of electricity and magnetism.",
                "category": "science",
                "slugName": "electricity-magnetism-lab",
                "providerSlug": "tech-tots-coding"
            },
            {
                "name": "Marine Biology Expedition",
                "description": "Explore marine ecosystems, marine life, and ocean conservation through engaging activities.",
                "category": "science",
                "slugName": "marine-biology-expedition",
                "providerSlug": "animal-safari"
            },
            {
                "name": "Archaeology Adventure",
                "description": "Uncover the mysteries of the past through archaeological digs and artifact exploration.",
                "category": "science",
                "slugName": "archaeology-adventure",
                "providerSlug": "nature-discovery"
            },
            {
                "name": "Math Puzzles and Games",
                "description": "Fun and challenging math puzzles and games to enhance mathematical skills.",
                "category": "science",
                "slugName": "math-puzzles-games",
                "providerSlug": "math-wizards"
            },
            {
                "name": "Ecology Explorers",
                "description": "Learn about ecological systems, biodiversity, and conservation through outdoor adventures.",
                "category": "science",
                "slugName": "ecology-explorers",
                "providerSlug": "nature-discovery"
            },
            {
                "name": "Chemical Engineering Creations",
                "description": "Hands-on activities exploring the principles of chemical engineering and material science.",
                "category": "science",
                "slugName": "chemical-engineering-creations",
                "providerSlug": "science-wonders"
            },
            {
                "name": "Computer Science Quest",
                "description": "Introduction to computer science concepts, algorithms, and problem-solving through interactive projects.",
                "category": "science",
                "slugName": "computer-science-quest",
                "providerSlug": "tech-tots-coding"
            }
        ]

        Offer = self.get_model('offers', 'Offer')
        Category = self.get_model('categories', 'Category')
        Provider = self.get_model('providers', 'Provider')

        image_prefix = 'https://activity-guide-files.s3.amazonaws.com'
        
        for item in to_create:
            Offer.objects.get_or_create(
                name=item['name'],
                description=item['description'],
                category=Category.objects.get(slug=item['category']),
                slug=item['slugName'],
                provider=Provider.objects.get(slug=item['providerSlug']),
                image=f'{image_prefix}/offers/{item['slugName']}.jpg'
            )

    dependencies = [
        ('offers', '0001_initial'),
        ('categories', '0002_basic_categories'),
        ('providers', '0002_basic_providers'),
    ]

    operations = [
        migrations.RunPython(custom_task, migrations.RunPython.noop),
    ]
