# Generated by Django 4.2.7 on 2023-12-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
