# Generated by Django 4.2.7 on 2023-12-18 22:26
from django.db import migrations


class Migration(migrations.Migration):
    def custom_task(self, schema_editor):
        Relationship = self.get_model('members', 'Relationship')
                
        relationships_to_create = [
            'Me',
            'Spouse',
            'Parent',
            'Child',
            'Sibling',
            'Other'
        ]
        for relationship in relationships_to_create:
            Relationship.objects.get_or_create(name=relationship)

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(custom_task, migrations.RunPython.noop),
    ]
